hepsi:	derle	calistir

derle:
		
	g++ -I	./include/	-o	./lib/Dugum.o	-c	./src/Dugum.cpp
	g++ -I	./include/	-o	./lib/SayiListesi.o	-c	./src/SayiListesi.cpp
	g++ -I	./include/	-o	./lib/ListeListesi.o	-c	./src/ListeListesi.cpp
	g++	-I	./include/	-o	./bin/veri	./lib/Dugum.o	./lib/SayiListesi.o	./lib/ListeListesi.o	./src/veri.cpp


calistir:
	./bin/veri